### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by orangejuce** [shariharan205/Motor-Imagery-Tasks-Classification-using-EEG-data#1]
Hi, the data in your project has the sizes of 1000 *25 *288 , I want to ask what is the meaning of 1000? Why do you use 1000 in your project?

**Comment by pengpengyang** [comment]
Hi, the data in your project has the sizes of 1000 *25 *288 , I want to ask what is the meaning of 1000? Why do you use 1000 in your project?
